name: "Realm Setup"

working-dir: /tmp/realm-setup
env:
  REALM_VERSION: "2.9.2-2"

checks:
  private-key: false
  requires-root: true


jobs:
  os-info:
    steps:
      - name: install or upgrade realm
        run: |
          set -e
          realm_version=""
          if [ -f "/usr/local/bin/realm" ]; then
            realm_version=$(realm -v | cut -d ' ' -f 2)
          fi

          if [ "$realm_version" = "$REALM_VERSION" ]; then
            echo "Realm $REALM_VERSION is already installed."
            exit 0
          fi

          echo "Installing Realm $REALM_VERSION..."
          curl -fsSL https://github.com/zhboner/realm/releases/download/v2.9.2-2/realm-x86_64-unknown-linux-gnu.tar.gz -o realm.tar.gz
          tar -xvf realm.tar.gz
          chmod +x realm
          mv realm /usr/local/bin/
          rm -f realm.tar.gz

          echo "Realm $REALM_VERSION installed successfully."
          realm -v

          if [ ! -f "/usr/local/etc/realm/realm.toml" ]; then
            mkdir -p /usr/local/etc/realm/
            cat <<EOF > /usr/local/etc/realm/realm.toml
            [network]
            use_udp = false
            zero_copy = true
            fast_open = false
            tcp_timeout = 300
            udp_timeout = 30
            send_proxy = false
            send_proxy_version = 2
            accept_proxy = false
            accept_proxy_timeout = 5
            ipv6_only = false

            #[[endpoints]]
            #listen = "[::]:10341"
            #remote = "ipv4:30005"
            EOF
          fi

          if [ ! -f "/etc/systemd/system/realm.service" ]; then
            cat <<EOF > /etc/systemd/system/realm.service
            [Unit]
            Description=Realm Server
            After=network.target
            Wants=network-online.target systemd-networkd-wait-online.service

            [Service]
            Type=simple
            User=root
            Restart=on-failure
            RestartSec=5s
            DynamicUser=true
            ExecStart=/usr/local/bin/realm -c /usr/local/etc/realm/realm.toml

            [Install]
            WantedBy=multi-user.target
            EOF

            systemctl daemon-reload
            systemctl enable realm
          fi

          systemctl restart realm

          echo "Realm server installed and started successfully."
          sleep 2
          systemctl status realm --no-pager
     
      - name: clean up
        run: |
          echo "clean up done"

