name: "SS-Rust Setup"

working-dir: /tmp/ss-rust-setup
env:
  SS_VERSION: "1.23.5"

checks:
  private-key: false
  requires-root: true


jobs:
  os-info:
    steps:
      - name: install or upgrade ss-rust
        run: |
          set -e
          ss_version=""
          if [ -f "/usr/local/bin/ssserver" ]; then
            ss_version=$(ssserver -V | cut -d ' ' -f 2)
          fi

          if [ "$ss_version" = "$SS_VERSION" ]; then
            echo "SS-Rust $SS_VERSION is already installed."
            exit 0
          fi

          echo "Installing SS-Rust $SS_VERSION..."
          curl -fsSL https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.23.5/shadowsocks-v1.23.5.x86_64-unknown-linux-gnu.tar.xz -o ss-rust.tar.xz
          tar -xvf ss-rust.tar.xz
          chmod +x ssserver
          mv ssserver /usr/local/bin/
          rm -f ss-rust.tar.xz

          echo "SS-Rust $SS_VERSION installed successfully."
          ssserver -V

          if [ ! -f "/usr/local/etc/ss-rust/server.json" ]; then
            mkdir -p /usr/local/etc/ss-rust/
            psk=$(openssl rand -base64 32)
            cat <<EOF > /usr/local/etc/ss-rust/server.json
          {
              "server": "::0",
              "server_port": 30000,
              "password": "$psk",
              "method": "2022-blake3-aes-256-gcm"
          }
          EOF

          fi

          if [ ! -f "/etc/systemd/system/ss-rust.service" ]; then
            cat <<'EOF' > /etc/systemd/system/ss-rust.service
          [Unit]
          Description=SS-Rust Server
          After=network.target
          
          [Service]
          Type=simple
          User=veda
          ExecStart=/usr/local/bin/ssserver -c /usr/local/etc/ss-rust/server.json
          Restart=on-failure
          
          [Install]
          WantedBy=multi-user.target
          EOF

            systemctl daemon-reload
            systemctl enable ss-rust
          fi

          systemctl restart ss-rust

          echo "SS-Rust server installed and started successfully."
          sleep 2
          systemctl status ss-rust --no-pager
     
      - name: clean up
        run: |
          echo "clean up done"

