name: "VPS Setup"

working-dir: /tmp/vps-setup
env:
  NAD_VERSION: "1.0.0"

checks:
  private-key: false
  args:
    - name: pub
      pattern: ".+" # value match regex


jobs:
  os-info:
    steps:
      - name: check environment
        run: |
          echo "version: ${VERSION}"
          if [ "$(id -u)" -ne 0 ]; then
            echo "Error: This script must be run as root or with sudo."
            exit 1
          fi
          echo "pub key: ${pub}"
      - name: install software
        run: |
          apt update
          apt -y install curl vim ufw nginx libnginx-mod-stream
          ufw allow ssh
          ufw allow 443/tcp
          ufw enable

          if which docker >/dev/null 2>&1; then
            echo "Docker command exists."
          else
            echo "install docker"
            apt remove -y $(dpkg --get-selections docker.io docker-compose docker-doc podman-docker containerd runc | cut -f1) || true

            curl -fsSL https://get.docker.com -o get-docker.sh
            chmod +x get-docker.sh
            ./get-docker.sh
          fi

      - name: add Users
        run: |
          if id "veda" &>/dev/null; then
            echo "User veda already exists"
          else
            echo "you need to create a simple password for new user veda"
            adduser veda
          fi
          usermod -aG sudo veda
          usermod -aG docker veda
          usermod -aG systemd-journal veda
          usermod -aG adm veda
          usermod -aG www-data veda
          chown -R root:www-data /var/www
          chmod -R 775 /var/www
          find /var/www -type d -exec chmod g+s {} \;

          sudo -u veda mkdir -p /home/veda/.ssh
          sudo -u veda chmod 700 /home/veda/.ssh
          echo "${pub}" | sudo -u veda tee /home/veda/.ssh/authorized_keys > /dev/null
          sudo -u veda chmod 600 /home/veda/.ssh/authorized_keys
      - name: clean up
        run: |
          echo "clean up done"

