name: "VPS Setup"

working-dir: /tmp/vps-setup
env:
  VERSION: "1.0.0"

checks:
  private-key: false
  args:
    - name: pub
      pattern: ".+" # value match regex


jobs:
  os-info:
    steps:
      - name: check environment
        run: |
          echo "version: ${VERSION}"
          if [ "$(id -u)" -ne 0 ]; then
            echo "Error: This script must be run as root or with sudo."
            exit 1
          fi
          echo "pub key: ${pub}"
      - name: install software
        run: |
          apt update
          apt -y install curl vim ufw nginx
          ufw allow ssh
          ufw allow 443/tcp
          ufw enable

          if which docker >/dev/null 2>&1; then
            echo "Docker command exists."
          else
            echo "install docker"
            apt remove -y $(dpkg --get-selections docker.io docker-compose docker-doc podman-docker containerd runc | cut -f1) || true

            curl -fsSL https://get.docker.com -o get-docker.sh
            chmod +x get-docker.sh
            ./get-docker.sh
          fi

      - name: add Users
        run: |
          adduser veda
          usermod -aG sudo veda
          usermod -aG docker veda

          sudo su - veda
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${pub}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          exit
      - name: clean up
        run: |
          echo "clean up done"

