name: "VPS Setup"

working-dir: /tmp/vps-setup
env:
  VERSION: "1.0.0"

checks:
  private-key: false
  args:
    - name: pub
      pattern: "[\\S]+" # value match regex


jobs:
  os-info:
    steps:
      - name: check environment
        run: |
          echo "version: ${VERSION}"
          if [ "$(id -u)" -ne 0 ]; then
            echo "Error: This script must be run as root or with sudo."
            exit 1
          fi
          echo "pub key: ${pub}"
      - name: install software
        run: |
          apt update
          apt -y install curl vim ufw nginx
          ufw allow ssh
          ufw allow 443/tcp
          ufw enable

          echo "install docker"
          apt remove -y $(dpkg --get-selections docker.io docker-compose docker-doc podman-docker containerd runc | cut -f1) || true

          # Add Docker's official GPG key:
          sudo apt update
          sudo apt -y install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF

          sudo apt update
          sudo apt -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: add Users
        run: |
          adduser veda
          usermod -aG sudo veda
          usermod -aG docker veda

          sudo su - veda
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${pub}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          exit
      - name: clean up
        run: |
          echo "clean up done"

